name: CI
on: push

jobs:
  publish:
    name: Build macOS macOS-10.14
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
  
      - name: Dump GitHub context
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" && echo "$GITHUB_REF"
  
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/v')
        # env:
        #   TAG: 
        #   SIZE: "$(stat -f%z build.sh)"
        run: |
          echo "TAG : $([[ ${{github.ref}} =~ ^refs/tags/(.+) ]] && ${BASH_REMATCH[1]})"
          echo "SIZE : $(stat -f%z build.sh)"

# - name: build pulsar ${{ matrix.os }} python mac libraries
#   run: |
#     ./build.sh

# - name: Upload
#   env:
#     TAG: $([[ ${{github.ref}} =~ ^refs/tags/(.+) ]] && ${BASH_REMATCH[1]})
#     SIZE: $(stat -c %s ./python/dist/pulsar_client-2.4.0-cp37-cp37m-macosx_10_14_x86_64.whl)
#   if: startsWith(github.ref, 'refs/tags/v')
#   run: 'curl -sSL -XPOST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Size: $SIZE" -H "Content-Type: application/zip" --upload-file ./python/dist/pulsar_client-2.4.0-cp37-cp37m-macosx_10_14_x86_64.whl https://uploads.github.com/repos/aahmed-se/pulsar-ci-test/releases/tag/${TAG}/assets?name=pulsar_client-2.4.0-cp37-cp37m-macosx_10_14_x86_64.whl'
  

# name: Build macOS ${{ matrix.os }}
# runs-on: ${{ matrix.os }}
# strategy:
#   matrix:
#     os: [macOS-10.14]

# run: 'curl -sSL -XPOST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Size: $SIZE" -H "Content-Type: application/zip" --upload-file ./build.sh https://uploads.github.com/repos/aahmed-se/pulsar-ci-test/releases/tag/${TAG}/assets?name=build.sh'
