on:
  push:
    branches:
    - master
  pull_request: 
    branches:
    - master

jobs:
  build_macos:
    name: Build MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: build pulsar python mac libraries
      run: |
        ./build.sh
