on: release
name: Handle Release

jobs:
  build_macos_10_14:
    name: Build macOS-10_14
    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: build pulsar macOS-10.14 python mac libraries
      run: |
        ./build.sh

    - uses: actions/checkout@master
    - name: Upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'pulsar/pulsar-client-cpp/**/*.whl'


# jobs:
#   upload:
#     name: Upload
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - name: Upload
#       uses: skx/github-action-publish-binaries@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         args: '*-*'